### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by datalorax** [ResearchTransparency/rr_aera19#2]
I edited the description file pretty heavily. Fine with going back to what you had too, but see what you think of what I did.

Also, I think we're a little over the word limit now, so if you could get it all down to 250 that would be awesome. As an aside, not sure if you use [sublimetext](https://www.sublimetext.com) but I think it's a lifesaver for things like this. With add-ins, you can make it do hard line breaks at 80 characters automatically which really helps with tracking changes to the text through GitHub. Also has spellcheck built in, as well as word count, etc. It's awesome. I love it.

I'll get to the other files starting tomorrow!

**Comment by jrosen48** [comment]
On it-and tnx for pointing me toward sublimetext. Will use it. Look for edits by tomorrow.

**Comment by datalorax** [comment]
BTW: [This](https://github.com/randy3k/AutoWrap) is the add-in you need for auto hard wrap with sublime text. (Need to install package control first) 

To have it spell check by default, modify your user settings to include `"spell_check": true`

**Comment by jrosen48** [comment]
I think you did an outstanding job with [`1_description.Rmd`](https://github.com/ResearchTransparency/rr_aera19/blob/master/I_description.Rmd). I just pushed two commits, one to fix a typo and mention that advanced researchers may want to train their students in reproducible research, and the second tipping our hat to idea of the replication crisis. What do you think of this latter change? How to position *this kind* of issue concerning reproducibility (relative to a reproducible workflow) is tricky. I think some folks (and perhaps reviewers) will be thinking about or looking for something on this latter issue and so I wonder if we can try to connect them. Thoughts?

**Comment by datalorax** [comment]
I think that’s a great idea. One of the ways we could position it is by talking about reproducibility as a *minimal* standard, that can also increase the likelihood of replicability (the gold standard). I actually had some text around this in the narrative but took it out because of space but I could easily add it back in. Roger Peng has talked a lot about it being a minimal standard. I like it because it’s a good compromise between what people usually do, nothing, and full-scale replication, while also providing a “recipe” for replication. (But long winded and ramble-y but this is from my phone)

**Comment by jrosen48** [comment]
Had to cut a lot, but got this down to (I think exactly) 250 words.
