### ISSUE TITLE
Using bibtex

### ISSUE THREAD

**Issue by jrosen48** [ResearchTransparency/rr_aera19#3]
I have never used bibtex before but I am very interested in using it. If I make mistakes, just LMK, okay?

**Comment by datalorax** [comment]
What have you use in the past? It's the only thing I've ever used so I'm not even aware of alternatives. Would be happy to adapt to your workflow if that's easier.

**Comment by jrosen48** [comment]
A big word doc with a bunch of text (ugh! So I really haven't used anything well or systematically). I'd really like to use bibtex but haven't had a good chance/time to learn it. This is good opportunity for me to.

**Comment by datalorax** [comment]
Okay, I take back my earlier comment. I do not want to adapt to your workflow 😳😉

Absout to start working on doc II
